Regressão linear - Custo da diaria de um imovel x numero de pessoas.

In [77]:
# Bibliotecas que vou utilizar:
import pandas as pd
import plotly.express as px
import seaborn as sns
import numpy as np


Abrindo o arquivo csv.

In [5]:
base_custo_diaria = pd.read_csv('base_custo_diaria.csv', sep= ';')

Visualizando informações:

In [6]:
base_custo_diaria.head

<bound method NDFrame.head of     qtd_pessoas  valor_diaria
0             1           150
1             3           200
2             4           650
3             6           499
4             7           549
5            10           980
6            12           700
7            13           735
8            15           859
9            16           900
10           20          1100
11           18           989
12           22          1075
13           23          1378
14           25          1500
15           27          1755
16           30          1850
17           32          2500
18           33          2000
19           40          1900
20           42          2089
21           43          2500
22           45          2250
23           47          2488
24           50          2680
25           51          2803
26           52          2890
27           53          3040
28           58          3150
29           60          3300>

**Informações estátisticas**

In [7]:
base_custo_diaria.describe()

qtd_pessoas  valor_diaria
count    30.000000     30.000000
mean     28.600000   1648.633333
std      18.189804    950.522197
min       1.000000    150.000000
25%      13.500000    869.250000
50%      26.000000   1627.500000
75%      44.500000   2497.000000
max      60.000000   3300.000000

Variavel independente (x) - machine learning.

In [19]:
X_custo_diaria = base_custo_diaria.iloc[:,0].values
X_custo_diaria
#estamos buscando a coluna quantidade de pessoas.

array([ 1,  3,  4,  6,  7, 10, 12, 13, 15, 16, 20, 18, 22, 23, 25, 27, 30,
       32, 33, 40, 42, 43, 45, 47, 50, 51, 52, 53, 58, 60])

Predição- variavel dependente (y).

In [53]:
y_custo_diaria = base_custo_diaria.iloc[:,1].values #2º coluna 
y_custo_diaria

array([ 150,  200,  650,  499,  549,  980,  700,  735,  859,  900, 1100,
        989, 1075, 1378, 1500, 1755, 1850, 2500, 2000, 1900, 2089, 2500,
       2250, 2488, 2680, 2803, 2890, 3040, 3150, 3300])

Existe correlação entre as variavies?

In [23]:
np.corrcoef(X_custo_diaria,y_custo_diaria) #matriz

array([[1.        , 0.97866601],
       [0.97866601, 1.        ]])

Tratamento dos dados.

In [29]:
X_custo_diaria.shape


(30,)

In [32]:
X_custo_diaria

array([ 1,  3,  4,  6,  7, 10, 12, 13, 15, 16, 20, 18, 22, 23, 25, 27, 30,
       32, 33, 40, 42, 43, 45, 47, 50, 51, 52, 53, 58, 60])

In [35]:
X_custo_diaria = X_custo_diaria.reshape(-1,1)
X_custo_diaria

array([[ 1],
       [ 3],
       [ 4],
       [ 6],
       [ 7],
       [10],
       [12],
       [13],
       [15],
       [16],
       [20],
       [18],
       [22],
       [23],
       [25],
       [27],
       [30],
       [32],
       [33],
       [40],
       [42],
       [43],
       [45],
       [47],
       [50],
       [51],
       [52],
       [53],
       [58],
       [60]])

In [37]:
X_custo_diaria.shape

(30, 1)

Dados tratados para o algoritimo de regressão linear


In [55]:
from sklearn.linear_model import LinearRegression
previsao_custo_diaria = LinearRegression()

In [56]:
previsao_custo_diaria.fit(X_custo_diaria, y_custo_diaria)

LinearRegression()

E(Y | Xi) = ***α*** + β*X - Localizando a constante da equação

In [57]:
previsao_custo_diaria.intercept_

186.00229281307384

E(Y | Xi) = α + β*X - Localizando a coeficiente angular da equação

In [58]:
previsao_custo_diaria.coef_

array([51.14094547])

In [64]:
previsao_precos = previsao_custo_diaria.predict(X_custo_diaria)
previsao_precos

array([ 237.14323829,  339.42512923,  390.5660747 ,  492.84796565,
        543.98891112,  697.41174754,  799.69363849,  850.83458396,
        953.1164749 , 1004.25742038, 1208.82120227, 1106.53931132,
       1311.10309321, 1362.24403869, 1464.52592963, 1566.80782058,
       1720.230657  , 1822.51254794, 1873.65349341, 2231.64011172,
       2333.92200267, 2385.06294814, 2487.34483909, 2589.62673003,
       2743.04956645, 2794.19051192, 2845.3314574 , 2896.47240287,
       3152.17713023, 3254.45902118])

In [65]:
X_custo_diaria

array([[ 1],
       [ 3],
       [ 4],
       [ 6],
       [ 7],
       [10],
       [12],
       [13],
       [15],
       [16],
       [20],
       [18],
       [22],
       [23],
       [25],
       [27],
       [30],
       [32],
       [33],
       [40],
       [42],
       [43],
       [45],
       [47],
       [50],
       [51],
       [52],
       [53],
       [58],
       [60]])

In [70]:
X_custo_diaria.ravel()


array([ 1,  3,  4,  6,  7, 10, 12, 13, 15, 16, 20, 18, 22, 23, 25, 27, 30,
       32, 33, 40, 42, 43, 45, 47, 50, 51, 52, 53, 58, 60])

In [71]:
y_custo_diaria

array([ 150,  200,  650,  499,  549,  980,  700,  735,  859,  900, 1100,
        989, 1075, 1378, 1500, 1755, 1850, 2500, 2000, 1900, 2089, 2500,
       2250, 2488, 2680, 2803, 2890, 3040, 3150, 3300])

Visualização de gráfico

In [81]:
grafico = px.scatter(x = X_custo_diaria.ravel(),y = y_custo_diaria)
grafico.show


<bound method BaseFigure.show of Figure({
    'data': [{'hovertemplate': 'x=%{x}<br>y=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'symbol': 'circle'},
              'mode': 'markers',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': array([ 1,  3,  4,  6,  7, 10, 12, 13, 15, 16, 20, 18, 22, 23, 25, 27, 30, 32,
                          33, 40, 42, 43, 45, 47, 50, 51, 52, 53, 58, 60]),
              'xaxis': 'x',
              'y': array([ 150,  200,  650,  499,  549,  980,  700,  735,  859,  900, 1100,  989,
                          1075, 1378, 1500, 1755, 1850, 2500, 2000, 1900, 2089, 2500, 2250, 2488,
                          2680, 2803, 2890, 3040, 3150, 3300]),
              'yaxis': 'y'}],
    'layout': {'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis':

In [94]:
grafico = px.scatter(x = X_custo_diaria.ravel(),y = y_custo_diaria)
grafico.add_scatter(x = X_custo_diaria.ravel(),y = previsao_precos, name= 'previsão')
grafico.show()

In [84]:
qt_pessoas = 4
previsao_custo_diaria.intercept_ + previsao_custo_diaria.coef_ * 4


array([390.5660747])

In [96]:
qt_pessoas = 25
previsao_custo_diaria.intercept_ + previsao_custo_diaria.coef_ * 25

array([1464.52592963])

In [87]:
#Qualidade do modelo
previsao_custo_diaria.score(X_custo_diaria, y_custo_diaria)

0.9577871649322629

Erros presentes no modelo

In [97]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
MSE = mean_squared_error(y_custo_diaria, previsao_precos)


In [89]:
MSE

36867.67840031127